### ISSUE TITLE
Missing Handle prefix not being logged to handle.log

### ISSUE THREAD

**Issue by amrri06** [curationexperts/mira#649] opened 2015-06-23 19:10 UTC
I published 853 to display in Tisch and DL and expected a handle to be generated.  No handle was generated.

Alicia Morris

**Comment by mark-dce** [comment] 2015-06-26 22:26
On mira.curationexperts.com

```text
$ RAILS_ENV=production bundle exec rake handle:register[tufts:967]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
Registering a handle for tufts:967
rake aborted!
Settingslogic::MissingSetting: Missing setting 'handle_prefix' in /opt/mira/releases/20150626221444/config/application.yml
/opt/mira/shared/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:189:in `missing_key'
/opt/mira/shared/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:117:in `method_missing'
/opt/mira/shared/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:66:in `method_missing'
/opt/mira/releases/20150626221444/app/services/register_handle_service.rb:57:in `handle_prefix'
/opt/mira/releases/20150626221444/app/services/register_handle_service.rb:61:in `generate_handle'
/opt/mira/releases/20150626221444/app/services/register_handle_service.rb:11:in `run'
/opt/mira/releases/20150626221444/lib/tasks/handle.rake:11:in `block (2 levels) in <top (required)>'
Tasks: TOP => handle:register
(See full trace by running task with --trace)
```

**Comment by mark-dce** [comment] 2015-06-26 22:35
This pid should have had a handle generated on publish, but did not.  When I tried to register it manually from the command line, I got the error above.

There's nothing in the handle.log to suggest there was a problem and there are no resque job errors associated with the failed registration job.

I'm adding the missing prefix to `application.yml` but this type of error should be logged in the handle log so the issue is easier to detect and correct.

**Comment by mark-dce** [comment] 2015-06-26 22:45
Any of the required handle configuration parameters should cause a log entry to be created when a handle should be generated on publish:

* handle_prefix: 
* handle_private_key: 
* handle_batch_tool:  
* handle_email:         
 * handle_admin:

**Comment by mark-dce** [comment] 2015-06-26 23:04
@amrri06 - I have fixed handle generation on the testing server, so you should be able to continue testing this.  I have left the ticket open and added some additional diagnostic information though, because I discovered that there were certain mis-configurations that weren't getting logged to the handle.log file.

Basically, once the service is set up and running correctly you would never see these errors, but it would be nice to have them logged just in case someone new is ever setting up a new server.

In this case, the specific issue was that we had an older version of a config file that had `handle_password:` configured instead of `handle_passphrase:` which is the correct entry.

**Comment by acozine** [comment] 2015-06-29 20:18
This was a config error on mira.curationexperts.com. We tracked it in resque-web. The error was:
Exception: Settingslogic::MissingSetting
Error: Missing setting 'handle_prefix' in /opt/mira/releases/20150626221444/config/application.yml
Fixed now. This particular error should not come up once your production config/application.yml file is correct.

**Closed** 2015-06-29 22:02 UTC
