### ISSUE TITLE
template import batch missing image pids

### ISSUE THREAD

**Issue by acozine** [curationexperts/mira#567] opened 2015-06-05 15:59 UTC
Steps to reproduce:
On devmira, select Start a Template-based import
Select the template Importing images and the object type Images
Select the files CastoriaAd.tiff, Interior view of the Barnum Museum . . . .tiff, and JumboPrint.tiff from 
https://drive.google.com/open?id=0BytolfRBVL3rcE1IajJISWVJNWs
and upload.
See batches 40, 44, and 45 for examples.
Cannot reproduce (so far) with other templates and these files, or with other files on this template.

**Comment by acozine** [comment] 2015-06-05 16:18
Gist here https://gist.github.com/acozine/37f5931176b41dbfcc69 includes:
* log output for a successful batch upload of three images on a different template
* log output for a batch upload of the same three images on the failing template

**Comment by jcoyne** [comment] 2015-06-05 18:17
I can't duplicate this: http://devmira.curationexperts.com/batch/template_imports/51

**Comment by acozine** [comment] 2015-06-05 19:37
Looks like this error is connected to timing. If you click on Batch Summary before all the files have uploaded or immediately after the last file uploads, it can interrupt the flow. Suggested fix: 
Make Batch Summary button disabled until all PIDs have been added to the batch.

**Comment by acozine** [comment] 2015-06-05 19:39
Hard to reproduce on a local system. Use devmira with one large file and a few smaller ones, or use lots of local files.

**Comment by tonyc** [comment] 2015-06-09 21:12
Unable to reproduce. Closing.

**Closed by tonyc** 2015-06-09 21:12 UTC
Labels: bug, in progress
