### ISSUE TITLE
Self-deposit form is broken

### ISSUE THREAD

**Issue by val99erie** [curationexperts/mira#368] opened 2015-04-10 17:53 UTC
Steps to reproduce the problem:

1. Log in to MIRA as a non-admin user
2. Visit http://localhost:3000/contribute
3. Hit "Begin" button for a Faculty Scholarship
4. Under "PDF to upload", select a PDF file to upload
5. Fill in the rest of the form and submit it
6. Notice the error message.  File type is not correct and the file's name seems to be blank in the error message:

![self_deposit_error](https://cloud.githubusercontent.com/assets/298865/7093651/ac36e4a6-df80-11e4-942e-23ba28961d34.png)

**Comment by val99erie** [comment] 2015-04-10 18:55
Note:  I also see this behavior in the "oldmira" sandbox, which is on commit "863f63b", deployed 10/23/2014 according to Alicia.

**Comment by val99erie** [comment] 2015-04-10 19:53
I also see this behavior when doing a batch template import or XML import.

**Comment by val99erie** [comment] 2015-04-10 19:53
Question:  Is this happening in Tufts' production MIRA ?  Or is this a problem with our environments and/or the current master branch?

**Comment by mkorcy** [comment] 2015-04-10 20:14
@val99erie no i've been working on self-deposit this week too and I haven't seen this. I just verified against mira-dev as well

**Comment by mkorcy** [comment] 2015-04-10 20:17
tried Firefox, and safari in addition to Chrome as well.

**Comment by val99erie** [comment] 2015-04-10 20:22
@mkorcy  ok thanks for the info.  Must be something wrong with my environment or branch

**Comment by val99erie** [comment] 2015-04-13 16:59
This might only be a problem with Firefox.  I'll try to get more details after I finish my current story.

**Comment by acozine** [comment] 2015-04-23 14:46
Closing - can't reproduce.

**Closed** 2015-04-23 14:46 UTC
Labels: bug
