### ISSUE TITLE
XML Import show page is broken

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/mira#502] opened 2015-05-29 16:43 UTC
http://devmira.curationexperts.com/batch/xml_imports/25

**Comment by jcoyne** [comment] 2015-05-29 17:01
```
ActionView::Template::Error (No such file or directory @ rb_sysopen - /opt/mira/releases/20150529144357/uploads/production/batch_xml_import/metadata_file/25/tufts_RCR00579.xml):
     5:
     6:   <%= link_to "All batches", batches_path %>
     7:
     8:   <% missing = @batch.missing_files %>
     9:   <% unless missing.blank? %>
    10:     <div class="alert alert-warning">
    11:       <strong>Warning:</strong> Metadata exists for the following files that have not been updated:<br/>
  app/views/batch/xml_imports/show.html.erb:8:in `_app_views_batch_xml_imports_show_html_erb___3642245245265384389_77112680'
```

**Comment by val99erie** [comment] 2015-05-29 18:30
I'm not able to reproduce this error on master, but in the case where there are files missing from the batch, I got a different error:

 Showing /Users/valerie/valerie/program/workspace/dce/code/tufts/mira/app/views/batch/xml_imports/show.html.erb where line #17 raised:
undefined method `edit_batch_path'

**Comment by val99erie** [comment] 2015-05-29 18:34
Per @jcoyne this is probably related to old deployment setup.  I will close the issue.

**Closed by val99erie** 2015-05-29 18:34 UTC
Labels: bug
